from __future__ import annotations

import ast
import dis
import getpass
import hashlib
import html
import importlib.metadata
import json
import linecache
import os
import platform
import re
import struct
import sys
import uuid
import zlib
from collections.abc import Callable
from copy import deepcopy
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any, cast

import altair as alt

from . import discovery

if TYPE_CHECKING:
    import pandas as pd
    import polars as pl

from .utils import _frame_checksum as frame_checksum

# The public ds.metadata API. Everything else here is internal (underscore or not).
__all__ = ["VerifyResult", "frame_checksum", "read", "verify"]

_REPORT_PREFIX = "dysonsphere-report-"
_STAT_OWNER_PREFIX = "__dsstatistics_owner_"

# Namespace for the derived (reproducible-build) exportIdentifier - see `_derive_export_id`.
_EXPORT_ID_NAMESPACE = "https://github.com/dkkung/dysonsphere/export/"


# ── Writing metadata into output files ───────────────────────────────────────


def _inject_png_metadata(png_bytes: bytes, text: str, keyword: str = "Description") -> bytes:
    """Insert an iTXt chunk (``keyword`` → ``text``) immediately after the IHDR chunk.

    Used for both the human-readable ``Description`` and the machine-readable
    ``dysonsphere`` JSON payload.  iTXt supports UTF-8 text (unlike tEXt which is
    Latin-1 only).  The chunk is inserted after IHDR so metadata-aware readers
    encounter it before any pixel data.  All existing chunks and their CRCs are left
    unchanged; only the new chunk's CRC is computed here.
    """
    chunk_type = b"iTXt"
    data = (
        keyword.encode("latin-1")
        + b"\x00"  # keyword + null terminator
        + b"\x00"  # compression flag: 0 (uncompressed)
        + b"\x00"  # compression method: 0
        + b"\x00"  # language tag: empty + null
        + b"\x00"
        + text.encode("utf-8")  # translated keyword: empty + null + text
    )
    crc = zlib.crc32(chunk_type + data) & 0xFFFFFFFF
    chunk = struct.pack(">I", len(data)) + chunk_type + data + struct.pack(">I", crc)

    # Locate end of IHDR: signature(8) + length(4) + type(4) + data(ihdr_len) + crc(4)
    ihdr_data_len = struct.unpack(">I", png_bytes[8:12])[0]
    insert_at = 8 + 4 + 4 + ihdr_data_len + 4

    return png_bytes[:insert_at] + chunk + png_bytes[insert_at:]


def _render_provenance(prov: dict[str, Any]) -> str:
    """Render the structured provenance dict as a human-readable ``report.provenance``
    section (title + underline + a 'Generated by …' sentence + the content checksum and
    export identifier), matching the statistics report style.
    """
    title = "Provenance"
    deps = prov["environment"]
    used = deps.get("dysonsphere-extensions")
    ext_clause = (", dysonsphere-extensions: " + ", ".join(f"{n} {v}" for n, v in used.items())) if used else ""
    sentence = (
        f"Generated by {prov['user']} with {prov['script']} on {prov['timestamp']} "
        f"using {deps['os']}, Python {deps['python']}, Altair {deps['altair']}, "
        f"vl-convert {deps['vl_convert']}, dysonsphere {deps['dysonsphere']}{ext_clause}, "
        f"NumPy {deps['numpy']}, SciPy {deps['scipy']}, Polars {deps['polars']}."
    )
    data_sums = prov["dataChecksum"]
    if len(data_sums) == 1:
        data_line = f"\nData checksum: {data_sums[0]}"
    elif data_sums:
        data_line = "\nData checksums:" + "".join(f"\n  - {s}" for s in data_sums)
    else:
        data_line = ""
    return (
        f"{title}\n{'─' * len(title)}\n\n{sentence}"
        f"{data_line}"
        f"\nVega-Lite spec checksum: {prov['vegaliteChecksum']}"
        f"\nExport identifier: {prov['exportIdentifier']}"
    )


def _call_expression(frame) -> str | None:
    """Best-effort source text of the ``chart`` argument at the caller's ``save(...)`` call
    site — the variable name (``"fig"``) or the inline composition (``"boxplot + points"``,
    a whole lambda), captured verbatim for ``provenance.chart``.

    How: the caller ``frame``'s currently-executing instruction is the CALL into ``save()``;
    its PEP 657 fine-grained position (Python 3.11+) spans the exact ``save(...)`` expression
    in the source. That segment is recovered via ``linecache`` (which also serves Jupyter cell
    source), parsed with ``ast``, and the first positional argument's (or ``chart=`` keyword's)
    own source segment is returned.

    Returns ``None`` — the field is then omitted — whenever the source is unavailable (plain
    REPL, ``exec``'d strings, frozen apps) or anything else fails: this is convenience
    metadata about the *source code* (a sibling of ``script``), never chart identity (the
    checksums are), so it fails silently rather than ever failing a save. Known honest
    limitation: it records the expression *at the call site*, so a wrapper function's
    ``ds.save(chart, ...)`` records the wrapper's parameter name ``"chart"``, not the
    caller-of-the-wrapper's composition.
    """
    try:
        # The last instruction at or before f_lasti is the executing CALL: f_lasti can point
        # into the CALL's inline CACHE entries (3.11 adaptive bytecode), which dis skips.
        positions = None
        for instr in dis.get_instructions(frame.f_code):
            if instr.offset > frame.f_lasti:
                break
            positions = instr.positions
        if positions is None or positions.lineno is None or positions.end_lineno is None:
            return None
        lines = linecache.getlines(frame.f_code.co_filename, frame.f_globals)
        if not lines or positions.end_lineno > len(lines):
            return None
        seg_lines = lines[positions.lineno - 1 : positions.end_lineno]
        seg_lines[-1] = seg_lines[-1][: positions.end_col_offset]
        seg_lines[0] = seg_lines[0][positions.col_offset :]
        segment = "".join(seg_lines)
        node = ast.parse(segment, mode="eval").body
        if not isinstance(node, ast.Call):
            return None
        if node.args:
            return ast.get_source_segment(segment, node.args[0])
        for kw in node.keywords:
            if kw.arg == "chart":
                return ast.get_source_segment(segment, kw.value)
        return None
    except Exception:
        return None


def _source_date_epoch() -> int | None:
    """The ``SOURCE_DATE_EPOCH`` build timestamp, or ``None`` when unset/empty.

    The reproducible-builds convention (https://reproducible-builds.org/specs/source-date-epoch/):
    an integer count of UTC seconds that pins every timestamp a build writes.  A malformed value
    raises rather than being ignored - silently falling back to the wall clock would hand back a
    non-reproducible export while the caller believes it is pinned.
    """
    raw = os.environ.get("SOURCE_DATE_EPOCH")
    if raw is None or not raw.strip():
        return None
    try:
        return int(raw.strip())
    except ValueError:
        raise ValueError(f"SOURCE_DATE_EPOCH must be an integer count of UTC seconds, got {raw!r}.") from None


def _resolve_timestamp() -> str:
    """The export timestamp, pinned to ``SOURCE_DATE_EPOCH`` when that is set."""
    epoch = _source_date_epoch()
    if epoch is None:
        return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    try:
        when = datetime.fromtimestamp(epoch, timezone.utc)
    except (OverflowError, OSError, ValueError):
        # Out of the platform's representable range - report it as the bad input it is.
        raise ValueError(f"SOURCE_DATE_EPOCH is out of range for a UTC timestamp: {epoch}.") from None
    return when.strftime("%Y-%m-%dT%H:%M:%SZ")


def _derive_export_id(timestamp: str, checksum: str, data_checksum: list[str]) -> str:
    """A content-derived ``exportIdentifier`` (UUIDv5), for reproducible builds.

    ``save()`` normally stamps a fresh ``uuid4`` so the variants of one export share a run id.
    That makes byte-identical re-exports impossible, so under ``SOURCE_DATE_EPOCH`` the id is
    derived instead: identical inputs yield an identical id, and distinct figures still differ
    because the spec checksum is part of the payload (two plots built from one dataframe in the
    same build must not collide).  Derived from the FIRST variant's ``checksum`` and reused for
    the rest, since ``vegaliteChecksum`` differs between the light and dark renders.
    """
    payload = f"{timestamp}|{checksum}|{','.join(data_checksum)}"
    return str(uuid.uuid5(uuid.NAMESPACE_URL, _EXPORT_ID_NAMESPACE + payload))


def _build_provenance(
    *,
    export_id: str,
    timestamp: str,
    checksum: str,
    data_checksum: list[str],
    extensions: dict[str, str],
    chart_expression: str | None,
) -> dict[str, Any]:
    """Collect the generation facts for the block.  ``export_id`` and ``timestamp`` are
    generated once per ``save()`` call (so every variant of one export shares them);
    ``checksum`` is per-variant (the SHA-256 of that variant's spec).  Field order is human-first:
    the readable who/when context (``user``/``script``/``chart``/``timestamp``) leads —
    ``chart`` (the best-effort call-site source text of the ``chart`` argument, from
    ``_call_expression``; omitted when ``None``) sits directly after ``script``, its sibling
    source-code fact — then ``environment`` —
    the platform + versioned toolchain (``os`` from ``platform.platform()`` first, then
    ``python``/``altair``/``vl_convert``/``dysonsphere``, then ``dysonsphere-extensions``
    ``{name: version}`` **directly after ``dysonsphere`` only when the figure actually used one**
    (e.g. ``ds.biology.volcano`` -> ``{"biology": "0.1.0"}``; see ``discovery._used_extensions`` -
    grouped with the tool it extends, and the explicit label disambiguates from a pypi 'extensions'
    package), then ``numpy``/``scipy``/``polars``: the OS, interpreter, spec generator, RENDERER,
    tool + its extensions, and runtime deps; ``os`` + ``vl_convert`` together pin *rendering*). Then
    finally the machine
    identity hashes: ``vegaliteChecksum`` (content identity, per variant), ``exportIdentifier`` (the
    run), and ``dataChecksum`` LAST (data identity, one entry per user frame, order-independent - the
    only unbounded field, so it trails, keeping the readable top of the block stable). This mirrors
    the ``_render_provenance`` prose, which also puts the checksums after the 'Generated by …'
    sentence.
    """
    try:
        _shell = get_ipython().__class__.__name__  # ty: ignore[unresolved-reference]
        script = "<jupyter-notebook>" if _shell == "ZMQInteractiveShell" else "<ipython>"
    except NameError:
        script = Path(sys.argv[0]).name or "<unknown-script>"
    try:
        user = getpass.getuser()
    except Exception:
        user = "unknown_user"
    return {
        "user": user,
        "script": script,
        # Best-effort call-site source of the `chart` argument (variable name or inline
        # composition); omitted when the source is unrecoverable.
        **({"chart": chart_expression} if chart_expression is not None else {}),
        "timestamp": timestamp,
        "environment": {
            "os": platform.platform(),
            "python": sys.version.split()[0],
            "altair": alt.__version__,
            "vl_convert": importlib.metadata.version("vl-convert-python"),
            "dysonsphere": importlib.metadata.version("dysonsphere"),
            # dysonsphere extensions that actually PRODUCED this figure (empty -> key omitted).
            # Grouped directly under `dysonsphere` (the tool + its extensions together); the explicit
            # `dysonsphere-extensions` label disambiguates from any pypi package named 'extensions'.
            **({"dysonsphere-extensions": extensions} if extensions else {}),
            "numpy": importlib.metadata.version("numpy"),
            "scipy": importlib.metadata.version("scipy"),
            "polars": importlib.metadata.version("polars"),
        },
        "vegaliteChecksum": checksum,
        "exportIdentifier": export_id,
        "dataChecksum": data_checksum,
    }


def _persistent_owner(name: object) -> str | None:
    """Return a persistent statistics owner from a view name, including extension wrappers."""
    _, underlying = discovery._unwrap_extension_markers(name)
    if not isinstance(underlying, str) or not underlying.startswith(_STAT_OWNER_PREFIX):
        return None
    owner = underlying[len(_STAT_OWNER_PREFIX) :]
    return owner if owner and re.fullmatch(r"[0-9a-f]{48}", owner) else None


_CHART_CHILD_KEYS = ("layer", "hconcat", "vconcat", "concat")


def _walk_chart_nodes(spec: dict[str, Any], visit: Callable[[dict[str, Any]], None]) -> None:
    """Walk Vega-Lite chart/spec nodes, never arbitrary data rows or metadata dictionaries."""
    visit(spec)
    for key in _CHART_CHILD_KEYS:
        children = spec.get(key)
        if isinstance(children, list):
            for child in children:
                if isinstance(child, dict):
                    _walk_chart_nodes(cast(dict[str, Any], child), visit)
    child = spec.get("spec")
    if isinstance(child, dict):
        _walk_chart_nodes(cast(dict[str, Any], child), visit)


_CONTEXT_ERROR = (
    "preserved statistical context changed; rebuild the annotation from its source data with "
    "ds.stats.comparisons() or ds.stats.correlation()"
)
_PRESENTATION_MARK = {
    "color",
    "fill",
    "stroke",
    "opacity",
    "fillOpacity",
    "strokeOpacity",
    "strokeWidth",
    "strokeDash",
    "size",
    "font",
    "fontSize",
    "fontStyle",
    "fontWeight",
    "align",
    "baseline",
    "dx",
    "dy",
    "angle",
    "cornerRadius",
    "cursor",
    "tooltip",
}
_PURE_EXPRESSION_FUNCTIONS = {
    "abs",
    "ceil",
    "clamp",
    "exp",
    "floor",
    "if",
    "indexof",
    "isFinite",
    "isNaN",
    "isValid",
    "length",
    "log",
    "lower",
    "max",
    "min",
    "pow",
    "replace",
    "round",
    "sqrt",
    "substring",
    "toNumber",
    "toString",
    "upper",
}


def _validate_statistics_expression(expression: str) -> None:
    """Accept only bounded, deterministic expressions over the current datum."""
    without_strings = re.sub(r"(['\"])(?:\\.|(?!\1).)*\1", "", expression)
    without_numbers = re.sub(
        r"(?<![\w$])(?:0[xX][0-9a-fA-F]+|(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)", "", without_strings
    )
    # Ignore only static dotted field names. Bracket contents remain tokenized because they may
    # themselves be computed expressions (datum[random()] must not look like a static field).
    without_dotted_fields = re.sub(r"(?<=\bdatum)\.[A-Za-z_$][\w$]*", "", without_numbers)
    identifiers = set(re.findall(r"[A-Za-z_$][\w$]*", without_dotted_fields))
    allowed = _PURE_EXPRESSION_FUNCTIONS | {"datum", "true", "false", "null"}
    if identifiers - allowed:
        raise ValueError(
            "unsupported statistical context: expressions may use only deterministic datum values and pure functions"
        )


def _validate_statistics_descriptor(value: Any) -> None:
    """Reject dataflow constructs whose runtime inputs cannot be guarded by a saved spec."""
    if isinstance(value, dict):
        if "lookup" in value:
            raise ValueError("unsupported statistical context: lookup transforms cannot be preserved")
        if "sample" in value:
            raise ValueError("unsupported statistical context: nondeterministic sample transforms cannot be preserved")
        if "param" in value or "selection" in value:
            raise ValueError("unsupported statistical context: runtime parameters and selections cannot be preserved")
        for key, child in value.items():
            if key in {"calculate", "expr"} and isinstance(child, str):
                _validate_statistics_expression(child)
            elif key in {"filter", "test"} and isinstance(child, str):
                _validate_statistics_expression(child)
            else:
                _validate_statistics_descriptor(child)
    elif isinstance(value, list):
        for child in value:
            _validate_statistics_descriptor(child)


def _statistics_context(spec: dict[str, Any], target: dict[str, Any]) -> str:
    """Hash the effective analytical leaves in the target owner's concat panel."""
    datasets: dict[str, Any] = (
        cast(dict[str, Any], spec.get("datasets")) if isinstance(spec.get("datasets"), dict) else {}
    )
    ancestors: list[dict[str, Any]] | None = None

    def locate(node: dict[str, Any], chain: list[dict[str, Any]]) -> None:
        nonlocal ancestors
        if node is target:
            ancestors = chain
            return
        for key in _CHART_CHILD_KEYS:
            for child in node.get(key, []) if isinstance(node.get(key), list) else []:
                if ancestors is None and isinstance(child, dict):
                    locate(child, [*chain, node])
        child = node.get("spec")
        if ancestors is None and isinstance(child, dict):
            locate(child, [*chain, node])

    locate(spec, [])
    if ancestors is None:
        raise ValueError("statistical owner is not part of the chart")
    panel = spec
    inherited_nodes: list[dict[str, Any]] = []
    for index, ancestor in enumerate(ancestors):
        if any(isinstance(ancestor.get(key), list) for key in ("hconcat", "vconcat", "concat")):
            panel = ancestors[index + 1] if index + 1 < len(ancestors) else target
            inherited_nodes = ancestors[: index + 1]

    def data_value(value: Any) -> Any:
        if value is None:
            return None
        if not isinstance(value, dict):
            raise ValueError("unsupported statistical context: data must be an object")
        if "url" in value:
            raise ValueError("unsupported statistical context: external data cannot be preserved")
        if isinstance(value.get("name"), str):
            name = value["name"]
            if name not in datasets:
                raise ValueError("unsupported statistical context: named data cannot be resolved")
            return {**{k: v for k, v in value.items() if k != "name"}, "values": datasets[name]}
        if "values" not in value:
            raise ValueError("unsupported statistical context: dynamic data cannot be preserved")
        return value

    def encoding_value(encoding: dict[str, Any]) -> dict[str, Any]:
        out: dict[str, Any] = {}
        for channel, definition in encoding.items():
            if channel in {"color", "fill", "stroke", "opacity", "size"} and isinstance(definition, dict):
                if "field" not in definition and "condition" not in definition and "expr" not in definition:
                    continue
            if not isinstance(definition, dict):
                out[channel] = definition
                continue
            item = {k: v for k, v in definition.items() if k not in {"axis", "legend"}}
            if isinstance(item.get("scale"), dict):
                scale = {k: v for k, v in item["scale"].items() if k not in {"range", "scheme"}}
                if scale:
                    item["scale"] = scale
                else:
                    item.pop("scale")
            out[channel] = item
        return out

    inherited: dict[str, Any] = {}
    inherited_transforms: list[Any] = []

    def reject_parameters(node: dict[str, Any]) -> None:
        if ("params" in node and node["params"] != []) or "selection" in node:
            raise ValueError("unsupported statistical context: runtime parameters and selections cannot be preserved")

    for node in inherited_nodes:
        reject_parameters(node)
        if "data" in node:
            inherited["data"] = data_value(node["data"])
        node_transforms = node.get("transform", []) if isinstance(node.get("transform"), list) else []
        _validate_statistics_descriptor(node_transforms)
        inherited_transforms.extend(node_transforms)
        if isinstance(node.get("encoding"), dict):
            _validate_statistics_descriptor(node["encoding"])
            inherited["encoding"] = {**inherited.get("encoding", {}), **encoding_value(node["encoding"])}
        for key in ("facet", "repeat"):
            if key in node:
                inherited[key] = node[key]

    leaves: list[Any] = []

    def collect(node: dict[str, Any], state: dict[str, Any]) -> None:
        from ._statistics import _marker_hash

        _, underlying = discovery._unwrap_extension_markers(node.get("name"))
        owner = _persistent_owner(node.get("name"))
        live_owner = _marker_hash(underlying) if isinstance(underlying, str) else None
        if node is not target and (owner is not None or live_owner is not None):
            return
        current = deepcopy(state)
        reject_parameters(node)
        if "data" in node:
            current["data"] = data_value(node["data"])
        transforms = node.get("transform")
        if isinstance(transforms, list):
            _validate_statistics_descriptor(transforms)
            current["transform"] = [*current.get("transform", []), *transforms]
        if isinstance(node.get("encoding"), dict):
            _validate_statistics_descriptor(node["encoding"])
            current["encoding"] = {**current.get("encoding", {}), **encoding_value(node["encoding"])}
        for key in ("facet", "repeat", "resolve"):
            if key in node:
                current[key] = node[key]
        children: list[dict[str, Any]] = []
        for key in _CHART_CHILD_KEYS:
            children.extend(child for child in node.get(key, []) if isinstance(child, dict))
        if isinstance(node.get("spec"), dict):
            children.append(node["spec"])
        if children:
            for child in children:
                collect(child, current)
            return
        mark = node.get("mark")
        if isinstance(mark, dict):
            analytical_mark = {k: v for k, v in mark.items() if k not in _PRESENTATION_MARK}
            _validate_statistics_descriptor(analytical_mark)
            current["mark"] = analytical_mark
        elif mark is not None:
            current["mark"] = mark
        leaves.append(current)

    inherited["transform"] = inherited_transforms
    collect(panel, inherited)
    serialized = sorted(json.dumps(leaf, sort_keys=True, separators=(",", ":")) for leaf in leaves)
    return hashlib.sha256(json.dumps(serialized, separators=(",", ":")).encode()).hexdigest()


def _prepare_statistics_owners(spec: dict[str, Any]) -> tuple[list[dict[str, Any]], dict[str, dict[str, str]]]:
    """Canonicalize available live/imported owners and return records in chart traversal order."""
    from ._statistics import _live_report, _loaded_report, _marker_hash, _record_hash

    selected: dict[str, dict[str, Any]] = {}
    bindings: dict[str, dict[str, str]] = {}
    occurrence = 0

    def prepare(node: dict[str, Any]) -> None:
        nonlocal occurrence
        name = node.get("name")
        _, underlying = discovery._unwrap_extension_markers(name)
        live_hash = _marker_hash(underlying) if isinstance(underlying, str) else None
        loaded_owner = _persistent_owner(name)
        record_hash = live_hash if live_hash is not None else (loaded_owner[:16] if loaded_owner is not None else None)
        saved_context = loaded_owner[16:32] if loaded_owner is not None else None
        record = (
            _live_report(record_hash)
            if live_hash is not None and record_hash is not None
            else (
                _loaded_report(record_hash, saved_context)
                if record_hash is not None and saved_context is not None
                else None
            )
        )
        if record is None:
            return
        actual_hash = _record_hash(record)
        context_hash = _statistics_context(spec, node)
        if saved_context is not None and context_hash[:16] != saved_context:
            raise ValueError(_CONTEXT_ERROR)
        occurrence += 1
        nonce = hashlib.sha256(f"{actual_hash}:{occurrence}".encode()).hexdigest()[:16]
        owner = actual_hash + context_hash[:16] + nonce
        node["name"] = f"{_STAT_OWNER_PREFIX}{owner}"
        selected.setdefault(actual_hash, record)
        bindings[owner] = {"record": actual_hash, "context": f"sha256:{context_hash}"}

    _walk_chart_nodes(spec, prepare)
    return list(selected.values()), bindings


def _restore_statistics_owners(spec: dict[str, Any]) -> tuple[dict[str, Any], list[tuple[dict[str, Any], str]]]:
    """Validate bindings transactionally and return a copy with fresh runtime owner identities."""
    from ._statistics import _record_hash

    restored = deepcopy(spec)
    usermeta = restored.get("usermeta")
    if usermeta is None:
        return restored, []
    if not isinstance(usermeta, dict):
        raise ValueError("saved usermeta must be an object")
    block = usermeta.get("dysonsphere")
    if block is None:
        return restored, []
    if not isinstance(block, dict):
        raise ValueError("saved dysonsphere metadata must be an object")
    if "statisticsBindings" not in block:
        return restored, []
    bindings = block["statisticsBindings"]
    records = block.get("statistics")
    if not isinstance(records, list) or not all(isinstance(record, dict) for record in records):
        raise ValueError("saved statisticsBindings require a statistics record list")
    from ._statistics import _render_report

    for record in records:
        try:
            json.dumps(record, allow_nan=False)
            if record.get("kind") not in {"pairwise", "omnibus", "correlation"}:
                raise ValueError
            checksum = record.get("dataChecksum")
            if checksum is not None and not (
                isinstance(checksum, str) and re.fullmatch(r"multiset-sha256:[0-9a-f]{64}", checksum)
            ):
                raise ValueError
            _render_report(record)
        except (KeyError, TypeError, ValueError, OverflowError) as error:
            raise ValueError("saved statistics contain a malformed record") from error
    by_hash = {_record_hash(record): record for record in records}
    if not isinstance(bindings, dict) or not all(
        isinstance(owner, str)
        and re.fullmatch(r"[0-9a-f]{48}", owner)
        and isinstance(binding, dict)
        and set(binding) == {"record", "context"}
        and isinstance(binding.get("record"), str)
        and re.fullmatch(r"[0-9a-f]{16}", binding["record"])
        and isinstance(binding.get("context"), str)
        and re.fullmatch(r"sha256:[0-9a-f]{64}", binding["context"])
        for owner, binding in bindings.items()
    ):
        raise ValueError("saved statisticsBindings must map owners to record and context identifiers")
    typed_bindings = cast(dict[str, dict[str, str]], bindings)
    if any(binding["record"] not in by_hash for binding in typed_bindings.values()):
        raise ValueError("saved statisticsBindings reference an unknown statistical record")
    if any(
        owner[:16] != binding["record"] or owner[16:32] != binding["context"][7:23]
        for owner, binding in typed_bindings.items()
    ):
        raise ValueError("saved statisticsBindings associate an owner with the wrong record")

    found: set[str] = set()

    def validate_owner(node: dict[str, Any]) -> None:
        if (owner := _persistent_owner(node.get("name"))) is not None:
            if owner not in typed_bindings:
                raise ValueError("saved chart contains an unbound statistical owner")
            found.add(owner)

    _walk_chart_nodes(restored, validate_owner)
    if found != set(typed_bindings):
        raise ValueError("saved statisticsBindings contain an owner absent from the chart")
    owner_nodes: dict[str, dict[str, Any]] = {}

    def collect_owner(node: dict[str, Any]) -> None:
        if (owner := _persistent_owner(node.get("name"))) is not None:
            owner_nodes[owner] = node

    _walk_chart_nodes(restored, collect_owner)
    for owner, node in owner_nodes.items():
        if _statistics_context(restored, node) != typed_bindings[owner]["context"][7:]:
            raise ValueError(_CONTEXT_ERROR)
    fresh_owners = {
        owner: binding["record"] + binding["context"][7:23] + uuid.uuid4().hex[:16]
        for owner, binding in typed_bindings.items()
    }

    def freshen(node: dict[str, Any]) -> None:
        if (owner := _persistent_owner(node.get("name"))) is not None:
            node["name"] = f"{_STAT_OWNER_PREFIX}{fresh_owners[owner]}"

    _walk_chart_nodes(restored, freshen)
    imported: dict[tuple[str, str], tuple[dict[str, Any], str]] = {}
    for binding in typed_bindings.values():
        key = (binding["record"], binding["context"][7:])
        imported.setdefault(key, (deepcopy(by_hash[binding["record"]]), binding["context"][7:]))
    return restored, list(imported.values())


def _strip_markers(spec, *, statistics_owners: bool = False) -> None:
    """Remove runtime markers from chart nodes, optionally including persistent statistics owners."""
    from ._statistics import _MARKER_PREFIX

    def strip_node(o: dict[str, Any]) -> None:
        name = o.get("name")
        marker_names, underlying_name = discovery._unwrap_extension_markers(name)
        if marker_names:
            name = underlying_name
            if name is None:
                del o["name"]
            else:
                o["name"] = name
        if isinstance(name, str) and name.startswith(_MARKER_PREFIX):
            del o["name"]
        elif statistics_owners and _persistent_owner(name) is not None:
            del o["name"]

    _walk_chart_nodes(spec, strip_node)


def _spec_checksum(spec) -> str:
    """``sha256:<hex>`` of the canonical Vega-Lite spec with ``usermeta`` removed.

    Runtime markers are already stripped. Persistent statistics owners retain their record and
    analytical-context hashes in canonical form but discard the fresh nonce, so ownership affects
    integrity while repeated loads remain reproducible. Sorted keys + compact separators make the
    result stable.
    """
    clean = deepcopy({k: v for k, v in spec.items() if k != "usermeta"})

    def normalize_owner(node: dict[str, Any]) -> None:
        if (owner := _persistent_owner(node.get("name"))) is not None:
            node["name"] = f"{_STAT_OWNER_PREFIX}{owner[:32]}"

    _walk_chart_nodes(clean, normalize_owner)
    canon = json.dumps(clean, sort_keys=True, separators=(",", ":"))
    return "sha256:" + hashlib.sha256(canon.encode()).hexdigest()


def _user_datasets(spec) -> dict[str, list[Any]]:
    """Every user (non-sidecar) inlined row-list in a spec, keyed by name.

    Collects named datasets (``spec["datasets"]``) then any inline ``data.values`` found by
    walking the tree (named ``inline-<i>``), and drops empty datasets plus dysonsphere's own
    internal sidecars — those carry the ``_INTERNAL_COL`` sentinel column.  Shared by
    ``_read_data`` and ``_data_checksum`` so both see the same set of user frames.
    """
    from .utils import _INTERNAL_COL

    named: dict[str, list[Any]] = {n: r for n, r in (spec.get("datasets") or {}).items() if isinstance(r, list)}
    _inline = [0]

    def walk(o):
        if isinstance(o, dict):
            d = o.get("data")
            if isinstance(d, dict) and isinstance(d.get("values"), list):
                named[f"inline-{_inline[0]}"] = d["values"]
                _inline[0] += 1
            for v in o.values():
                walk(v)
        elif isinstance(o, list):
            for v in o:
                walk(v)

    walk(spec)
    return {n: r for n, r in named.items() if r and _INTERNAL_COL not in r[0]}


def _data_checksum(spec) -> list[str]:
    """One ``multiset-sha256:<hex>`` per user dataframe, order-independent, as a sorted list.

    Unlike ``vegaliteChecksum`` (which changes with row order, since the inlined data is part
    of the spec it hashes), this ignores row order: it hashes the *multiset* of per-row
    canonical-JSON digests, so a reordered-but-identical frame yields the same value.  Duplicate
    rows are preserved.  Internal sidecar datasets are excluded, so the checksum is independent
    of how the data is drawn — two charts built from the same data match even across different
    marks/encodings/themes.  The list is sorted so multi-frame charts are order-independent too.
    """
    from .utils import _hash_rows

    out = [_hash_rows(rows) for rows in _user_datasets(spec).values()]
    return sorted(out)


def _build_block(
    records: list[Any],
    *,
    embed_report: bool,
    export_id: str,
    timestamp: str,
    checksum: str,
    data_checksum: list[str],
    extensions: dict[str, str],
    chart_expression: str | None,
    description: str | None,
    statistics_bindings: dict[str, dict[str, str]] | None = None,
) -> tuple[dict[str, Any], str, dict[str, str] | None]:
    """Assemble the ``dysonsphere`` metadata block from the drained statistical records.

    Returns ``(usermeta, usermeta_json, report_sections)``:

    - ``usermeta`` — ``{"dysonsphere": {provenance, statistics?, theme, report?, description?}}``
      for the Vega-Lite JSON ``usermeta`` (the ``report`` member is nested only here).
    - ``usermeta_json`` — the structured block *without* ``report``, serialized for the SVG
      ``<metadata>`` / PNG iTXt (those carry the report in dedicated readable channels).
    - ``report_sections`` — ``{section: text}`` (``statistics`` when there are records +
      ``provenance`` always), or ``None`` when ``embed_report`` is off.

    ``theme`` holds the resolved ``ds.theme()`` args (only ``_BUILTIN_DEFAULTS`` keys, so
    every one is a valid kwarg — dysonsphere params, never Altair's), letting ``load()``
    reconstruct the styling via ``ds.theme(**theme)``.

    ``description`` (the user's ``save(description=...)`` text) rides as the **last** member of
    the block in *both* channels — after ``report`` in the JSON ``usermeta``, and last in the
    report-free structured blob — so it is machine-readable from all three formats' embedded
    JSON (this is in addition to the native ``description``/``<desc>``/``iTXt Description``).

    ``statistics_bindings`` maps each compact persistent owner to its record and analytical-context
    hashes. Records remain serialized once in ``statistics`` rather than being copied into owners.
    """
    from ._statistics import _render_report
    from .theme import _BUILTIN_DEFAULTS

    provenance = _build_provenance(
        export_id=export_id,
        timestamp=timestamp,
        checksum=checksum,
        data_checksum=data_checksum,
        extensions=extensions,
        chart_expression=chart_expression,
    )
    ds_block: dict[str, Any] = {"provenance": provenance}
    if records:
        ds_block["statistics"] = records
    if statistics_bindings:
        ds_block["statisticsBindings"] = statistics_bindings
    ds_block["theme"] = {k: v for k, v in alt.theme.options.items() if k in _BUILTIN_DEFAULTS}
    # The SVG/PNG structured blob is report-free (they get per-section readable channels) but
    # DOES carry `description` — as the last member, mirroring the JSON.  ensure_ascii=False
    # keeps η²/─ literal.
    blob: dict[str, Any] = dict[str, Any](ds_block)
    if description is not None:
        blob["description"] = description
    usermeta_json = json.dumps(blob, ensure_ascii=False)
    report_sections: dict[str, str] | None = None
    if embed_report:
        report_sections = {}
        if records:
            report_sections["statistics"] = "\n\n".join(_render_report(r) for r in records)
        report_sections["provenance"] = _render_provenance(provenance)
        ds_block["report"] = report_sections  # rides only in the JSON usermeta (nested member)
    if description is not None:
        ds_block["description"] = description  # last key, after `report` in the JSON usermeta
    usermeta = {"dysonsphere": ds_block}
    return usermeta, usermeta_json, report_sections


def _svg_inserts(usermeta_json: str | None, report_sections: dict[str, str] | None, description: str | None) -> str:
    """Build the string injected after the opening ``<svg>`` tag: the structured
    ``<metadata id="dysonsphere">`` (CDATA), one readable ``<metadata id="dysonsphere-report-
    <section>">`` per section, and the user's ``<desc>``.  Empty when nothing to embed.
    """
    out = ""
    if usermeta_json is not None:
        out += f'<metadata id="dysonsphere"><![CDATA[{usermeta_json}]]></metadata>'
    if report_sections is not None:
        for section, text in report_sections.items():
            out += f'<metadata id="dysonsphere-report-{section}">{html.escape(text)}</metadata>'
    if description is not None:
        out += f"<desc>{html.escape(description)}</desc>"
    return out


def _inject_png_block(
    png_bytes: bytes, usermeta_json: str | None, report_sections: dict[str, str] | None, description: str | None
) -> bytes:
    """Inject the user ``Description``, the structured ``dysonsphere`` chunk, and one
    ``dysonsphere-report-<section>`` chunk per report section into the PNG.
    """
    if description is not None:
        png_bytes = _inject_png_metadata(png_bytes, description)
    if usermeta_json is not None:
        png_bytes = _inject_png_metadata(png_bytes, usermeta_json, keyword="dysonsphere")
    if report_sections is not None:
        # _inject_png_metadata prepends (each chunk lands right after IHDR), so inject in
        # reverse to leave the sections in section order — matching the JSON/SVG.
        for section, text in reversed(report_sections.items()):
            png_bytes = _inject_png_metadata(png_bytes, text, keyword=f"{_REPORT_PREFIX}{section}")
    return png_bytes


# ── Reading metadata back ────────────────────────────────────────────────────


def _iter_png_itxt(png_bytes: bytes):
    """Yield ``(keyword, text)`` for every PNG ``iTXt`` chunk."""
    i = 8  # skip the 8-byte PNG signature
    while i + 8 <= len(png_bytes):
        length = int.from_bytes(png_bytes[i : i + 4], "big")
        ctype = png_bytes[i + 4 : i + 8]
        chunk = png_bytes[i + 8 : i + 8 + length]
        if ctype == b"iTXt":
            kw, rest = chunk.split(b"\x00", 1)
            # keyword\0 + compflag/method/lang/transkw nulls + text
            yield kw.decode("utf-8"), rest.lstrip(b"\x00").decode("utf-8")
        if ctype == b"IEND":
            break
        i += 12 + length


def _read_png_text(png_bytes: bytes, keyword: str) -> str | None:
    """Return the UTF-8 text of the PNG ``iTXt`` chunk with ``keyword`` (or None)."""
    return next((t for kw, t in _iter_png_itxt(png_bytes) if kw == keyword), None)


def _read_dysonsphere_block(path: str | Path) -> dict[str, Any]:
    """Read the embedded ``usermeta.dysonsphere`` block from a dysonsphere-exported PNG,
    SVG, or Vega-Lite JSON (detected by extension), as the unified
    ``{provenance, statistics, theme, report}`` dict.  For SVG/PNG the ``report`` container
    (whose sections ride in their own readable channels) is merged back in.  Raises if none
    is found.
    """
    p = Path(path)
    ext = p.suffix.lower()
    if ext == ".json":
        block = (json.loads(p.read_text(encoding="utf-8")).get("usermeta") or {}).get("dysonsphere")
    elif ext == ".svg":
        svg = p.read_text(encoding="utf-8")
        m = re.search(r'<metadata id="dysonsphere"><!\[CDATA\[(.*?)\]\]></metadata>', svg, re.DOTALL)
        block = json.loads(m.group(1)) if m else None
        sections = {
            sec: html.unescape(txt)
            for sec, txt in re.findall(r'<metadata id="dysonsphere-report-([^"]+)">(.*?)</metadata>', svg, re.DOTALL)
        }
        if block is not None and sections:
            block["report"] = sections
    elif ext == ".png":
        data = p.read_bytes()
        struct_text = _read_png_text(data, "dysonsphere")
        block = json.loads(struct_text) if struct_text is not None else None
        sections = {kw[len(_REPORT_PREFIX) :]: t for kw, t in _iter_png_itxt(data) if kw.startswith(_REPORT_PREFIX)}
        if block is not None and sections:
            block["report"] = sections
    else:
        raise ValueError(f"read() supports .png, .svg, or .json files, got {p.suffix!r}")
    if block is None:
        raise ValueError(f"no dysonsphere metadata found in {path!r} — was it saved by ds.save()?")
    return block


_DATA_OUTPUTS = ("polars", "pandas", "duckdb", "records")


def _rows_as(rows: list[Any], output: str) -> Any:
    """Materialize a list of record dicts in the requested ``output`` form (pandas/duckdb
    imported lazily, with a clear error if missing)."""
    if output == "records":
        return rows  # raw list[dict] — no dataframe library needed
    if output == "pandas":
        try:
            import pandas as pd
        except ImportError as e:
            raise ImportError("read(output='pandas') requires pandas — `pip install pandas`.") from e
        return pd.DataFrame(rows)

    import polars as pl

    df = pl.DataFrame(rows)
    if output == "polars":
        return df
    try:  # duckdb
        import duckdb
    except ImportError as e:
        raise ImportError("read(output='duckdb') requires duckdb — `pip install duckdb`.") from e
    return duckdb.from_arrow(df.to_arrow())  # a queryable DuckDBPyRelation (pyarrow via polars)


def _read_data(path: str | Path, output: str, dataset: str | None) -> Any:
    """Rebuild the user's data from a Vega-Lite JSON (the ``.json`` spec).

    Altair inlines the whole ``alt.Chart(df)`` frame — **every column, even unused ones** —
    as named datasets.  dysonsphere's own composite marks/annotations also embed small
    internal sidecar datasets, each tagged with the ``_INTERNAL_COL`` sentinel; those are
    filtered out here so only the user's frame(s) remain.  ``dataset``: ``None`` (default)
    returns the single user frame — **raising** (with a listing) if there are ≥2, so a
    multi-frame chart is never silently truncated; ``"all"`` returns a ``{name: frame}`` dict;
    ``"<name>"`` returns one by name.  Each frame is materialized in the ``output`` form.
    """
    if output not in _DATA_OUTPUTS:
        raise ValueError(f"output must be one of {_DATA_OUTPUTS}, got {output!r}")
    p = Path(path)
    if p.suffix.lower() != ".json":
        raise ValueError(f"what='data' needs the Vega-Lite JSON (the .json spec), got {p.suffix!r}")
    spec = json.loads(p.read_text(encoding="utf-8"))

    # User frames = non-empty inlined datasets WITHOUT the internal sentinel column.
    user = _user_datasets(spec)

    if dataset == "all":
        return {n: _rows_as(r, output) for n, r in user.items()}
    if dataset is not None:
        if dataset not in user:
            raise ValueError(f"dataset {dataset!r} not found in {path!r}; available: {sorted(user)}")
        return _rows_as(user[dataset], output)
    if len(user) == 1:
        return _rows_as(next(iter(user.values())), output)
    if not user:
        raise ValueError(f"no user data found in {path!r} (was the DataFrame inlined at save time?)")
    listing = ", ".join(f"{n!r} ({len(r)} rows, cols {list(r[0])})" for n, r in user.items())
    raise ValueError(
        f"{len(user)} user datasets in {path!r}: {listing}. "
        f"Pass dataset='all' for a dict of all, or dataset='<name>' for one."
    )


def read(
    path: str | Path,
    *,
    what: str = "report",
    saveReport: bool | str | Path = False,
    output: str = "polars",
    dataset: str | None = None,
) -> Any:
    """Read back the metadata (or data) embedded by :func:`save` from a PNG, SVG, or JSON.

    Parameters
    ----------
    path:
        A dysonsphere-exported ``.png``, ``.svg``, or ``.json`` file.
    what:
        Which artifact to return:

        - ``'report'`` (default) — the human-readable report **table** as a ``str``;
          it is printed to stdout and returned. Joins every section of the ``report``
          container (``statistics`` + ``provenance``). Falls back to re-rendering the
          statistics from the embedded records if the prose wasn't saved
          (``embedReport=False``).
        - ``'statistics'`` — the structured **records** (list of dicts, exact floats).
        - ``'metadata'`` — the whole ``{provenance, statistics, theme, report}`` dict, where
          ``report`` is the ``{section: text}`` container.
        - ``'data'`` — the **original data** Altair inlined into the spec (the whole frame,
          including columns the chart never plotted). **JSON only** (PNG/SVG don't carry the
          data). The form is chosen by ``output``.
    saveReport:
        Only for ``what='report'``: ``True`` writes the report to a ``.txt`` in the cwd;
        a path writes to that directory.
    output:
        Only for ``what='data'`` — the form to return the data in: ``'polars'`` (default) →
        ``pl.DataFrame``; ``'pandas'`` → ``pd.DataFrame``; ``'duckdb'`` → a ``DuckDBPyRelation``;
        ``'records'`` → the raw ``list[dict]`` (no dataframe library needed). ``pandas`` and
        ``duckdb`` are imported lazily and are not package dependencies.

    Returns
    -------
    str, list[dict[str, Any]], dict[str, Any], or dataframe-like object
        The result selected by ``what`` and, for ``what='data'``, by ``output`` and ``dataset``.
    """
    if what == "data":
        return _read_data(path, output, dataset)
    block = _read_dysonsphere_block(path)
    if what == "metadata":
        return block
    if what == "statistics":
        return block.get("statistics", [])
    if what != "report":
        raise ValueError(f"what must be 'report', 'statistics', 'metadata', or 'data', got {what!r}")
    report = block.get("report")  # {section: text} container
    if report:
        text = "\n\n".join(report.values())
    else:  # prose wasn't embedded (embedReport=False) — re-render from records
        from ._statistics import _render_report

        text = "\n\n".join(_render_report(r) for r in block.get("statistics", []))
    print(text)
    if saveReport:
        directory = Path(saveReport) if not isinstance(saveReport, bool) else Path.cwd()
        directory.mkdir(parents=True, exist_ok=True)
        ts = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
        (directory / f"dysonsphere_report_{ts}.txt").write_text(text + "\n", encoding="utf-8")
    return text


@dataclass(frozen=True)
class VerifyResult:
    """Outcome of :func:`verify` - what could be checked, and what matched.

    ``specValid`` and ``dataMatches`` are **tri-state**: ``True``/``False`` when the check ran,
    and ``None`` when it could not run at all.  A check that was impossible is not a failure -
    an SVG or PNG carries no spec to re-hash, so ``specValid`` is ``None`` there, and
    ``dataMatches`` is ``None`` when no dataframe was supplied to compare against.

    Checking one figure fills ``path``/``specValid``/``dataMatches``; comparing a list fills
    ``matches``/``groups`` instead, and leaves ``path`` ``None`` since there is no single file.
    """

    path: str | None
    specValid: bool | None
    dataMatches: bool | None
    storedDataChecksums: list[str]
    computedDataChecksums: list[str]
    exportIdentifier: str | None
    timestamp: str | None
    matches: dict[str, bool | None] | None = None
    groups: dict[str, dict[str, int] | None] | None = None

    @property
    def ok(self) -> bool:
        """True when every integrity or comparison check that actually ran passed."""
        comparison_ok = self.matches is None or all(match is not False for match in self.matches.values())
        return self.specValid is not False and self.dataMatches is not False and comparison_ok


_COMPARE_KEYS = ("spec", "data", "save")


def _identities(item: Any, index: int) -> tuple[str, dict[str, str | None]]:
    """A label plus the three identities of one figure - a saved file or a chart in memory.

    A file reports what it recorded at save time.  A chart is measured directly, and has no
    ``save`` identity at all: it was never exported, so there is no export event to name.
    """
    from .utils import _hash_rows

    if isinstance(item, (str, Path)):
        prov = _read_dysonsphere_block(str(item)).get("provenance") or {}
        stored = prov.get("dataChecksum")
        return str(item), {
            "spec": prov.get("vegaliteChecksum"),
            "data": "|".join(sorted(stored)) if stored else None,
            "save": prov.get("exportIdentifier"),
        }
    if not hasattr(item, "to_dict"):
        raise TypeError(
            f"Item {index} is a {type(item).__name__}; each figure must be a path to a dysonsphere "
            f"export or an Altair chart."
        )
    from .utils import _apply_spec_fixes

    # save() runs the same spec transforms before hashing, so an in-memory chart has to go through
    # them too or it can never match the file it was saved to.
    spec = _apply_spec_fixes(item.to_dict())
    # Match save()'s record + analytical-context identity while discarding owner nonces.
    _prepare_statistics_owners(spec)
    _strip_markers(spec)
    frames = _user_datasets(spec)
    return f"chart[{index}]", {
        "spec": _spec_checksum({k: v for k, v in spec.items() if k != "usermeta"}),
        "data": "|".join(sorted(_hash_rows(rows) for rows in frames.values())) or None,
        "save": None,
    }


def _group_by_identity(labels: list[str], values: list[str | None]) -> dict[str, int] | None:
    """Number each figure by shared identity - same number, same figure.

    The numbers are assigned AFTER grouping on the full checksum, so two different figures can
    never share one.  A truncated checksum would read better but could collide, showing two
    different charts as identical.
    """
    if any(v is None for v in values):
        return None
    numbering: dict[str, int] = {}
    return {label: numbering.setdefault(cast(str, value), len(numbering)) for label, value in zip(labels, values)}


def verify(
    figure: Any,
    data: pl.DataFrame
    | pd.DataFrame
    | list[pl.DataFrame | pd.DataFrame]
    | tuple[pl.DataFrame | pd.DataFrame, ...]
    | None = None,
    *,
    what: str | tuple[str, ...] | list[str] = _COMPARE_KEYS,
) -> VerifyResult:
    """Check a saved figure against its own embedded checksums, and optionally against its data.

    Two independent questions, neither of which needs the original script:

    - **Is the file internally consistent?**  The spec is re-hashed and compared with the
      recorded ``vegaliteChecksum``, so an edited spec is detectable.  JSON only - SVG and PNG
      embed the metadata block but not the full spec, so ``specValid`` is ``None`` for them.
    - **Did this figure come from this data?**  Pass ``data`` and each frame's checksum is
      compared with the recorded ``dataChecksum``.  This works for **all three formats**, since
      the checksums travel in the metadata block, and it is order-independent in both senses:
      row order within a frame does not matter, nor does the order frames are passed in.

    ``exportIdentifier`` is reported, never checked.  It is a random UUID per ``save()`` call, or
    - under ``SOURCE_DATE_EPOCH`` - one derived from the figure's own content, in which case two
    saves of identical inputs share it by design.  Compare it across two files to ask whether they
    came from one save; compare ``vegaliteChecksum`` to ask whether they are the same chart.

    A file whose metadata is gone - screenshotted, or re-saved by a tool that drops it - cannot
    be checked at all: there is nothing to compare against, and this raises.  What survives is the
    trail for the DATA, because these checksums are recomputed from content rather than minted per
    file.  ``frame_checksum(data)`` returns the same value for the same rows forever, so a dataframe
    can still be matched against an intact sibling export or a checksum recorded elsewhere.

    Passing a **list** compares figures instead of checking one.  Each may be a saved file or a
    chart still in memory, in any mix.  ``what`` selects the questions - ``"spec"`` (the same
    chart, however it was exported), ``"data"`` (built from the same data), ``"save"`` (produced by
    one ``save()`` call) - and defaults to all three.  ``matches`` says whether every figure agrees
    on each; ``groups`` numbers them, so the same number means the same figure.  A chart in memory
    has no ``save`` identity, so that question comes back ``None`` for the whole call.

    Comparing reads what each file RECORDED, which is what lets a PNG be compared with a JSON -
    but it means an edited file still compares as the chart it claims to be.  Checking one figure
    on its own is what detects an edit; the two questions are deliberately separate.

    Parameters
    ----------
    figure:
        A dysonsphere-exported ``.png``, ``.svg``, or ``.json`` to check - or a list of figures
        to compare, each a path or an Altair chart.
    data:
        Optional dataframe, or list of dataframes, that the figure should have been built from.
        Polars or pandas.  Omit to check only the spec.
    what:
        Which questions to ask when comparing a list: any of ``"spec"``, ``"data"``, ``"save"``.
        Defaults to all three.  Ignored when checking a single figure.

    Returns
    -------
    VerifyResult
        ``.ok`` is ``True`` when every check that ran passed.  ``specValid``/``dataMatches`` are
        ``None`` for checks that could not run.

    Examples
    --------
    ::

        ds.metadata.verify("fig.json").ok                 # untampered?
        ds.metadata.verify("fig.png", data=data).dataMatches  # built from this data?
        ds.metadata.verify("fig.json", data=[counts, meta]) # multi-frame chart
    """
    if isinstance(figure, (list, tuple)):
        if data is not None:
            raise ValueError(
                "data= checks one figure against its data; it does not apply when comparing a list. "
                "Verify each figure separately, or drop data= to compare them with each other."
            )
        wanted = [what] if isinstance(what, str) else list(what)
        unknown = [w for w in wanted if w not in _COMPARE_KEYS]
        if unknown:
            raise ValueError(f"what has unknown name(s) {unknown}. Choose from {list(_COMPARE_KEYS)}.")
        if not wanted:
            raise ValueError(f"what must name at least one of {list(_COMPARE_KEYS)}.")
        if len(figure) < 2:
            raise ValueError("Comparing needs at least two figures; pass one on its own to check it.")
        pairs = [_identities(item, i) for i, item in enumerate(figure)]
        # The same path can appear twice; the labels key a dict, so repeats would overwrite each
        # other and the result would no longer describe the list that was passed.
        seen_labels: dict[str, int] = {}
        labels = []
        for label, _ in pairs:
            seen_labels[label] = seen_labels.get(label, 0) + 1
            labels.append(label if seen_labels[label] == 1 else f"{label} #{seen_labels[label]}")
        groups: dict[str, dict[str, int] | None] = {}
        matches: dict[str, bool | None] = {}
        for key in wanted:
            grouped = _group_by_identity(labels, [ids[key] for _, ids in pairs])
            groups[key] = grouped
            matches[key] = None if grouped is None else len(set(grouped.values())) == 1
        return VerifyResult(
            path=None,  # a comparison has no single path; the labels live in groups/matches
            specValid=None,
            dataMatches=None,
            storedDataChecksums=[],
            computedDataChecksums=[],
            exportIdentifier=None,
            timestamp=None,
            matches=matches,
            groups=groups,
        )

    path = figure
    block = _read_dysonsphere_block(path)
    prov = block.get("provenance") or {}
    stored = sorted(prov.get("dataChecksum") or [])

    spec_valid: bool | None = None
    if Path(path).suffix.lower() == ".json":
        spec = json.loads(Path(path).read_text(encoding="utf-8"))
        recorded = prov.get("vegaliteChecksum")
        if recorded is not None:
            # Re-hash exactly what save() hashed: the spec without usermeta.
            spec_valid = _spec_checksum({k: v for k, v in spec.items() if k != "usermeta"}) == recorded

    computed: list[str] = []
    data_matches: bool | None = None
    if data is not None:
        frames = data if isinstance(data, (list, tuple)) else [data]
        computed = sorted(frame_checksum(cast("pl.DataFrame | pd.DataFrame", f)) for f in frames)
        data_matches = computed == stored

    return VerifyResult(
        path=str(path),
        specValid=spec_valid,
        dataMatches=data_matches,
        storedDataChecksums=stored,
        computedDataChecksums=computed,
        exportIdentifier=prov.get("exportIdentifier"),
        timestamp=prov.get("timestamp"),
    )
